### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by jonchargreaves** [marthoc/GarHAge#15]
Hi, I have got to the home assistant integration, however everytime I paste the config into configuration.yaml I receive 

Invalid config

The following components and platforms could not be set up:

    mqtt
    cover.mqtt

Please check your config

I installed Home Assistant via Hassio and enabled the MQQT via the Hassio addons section, any help would be gratefully received!

**Comment by jonchargreaves** [comment]
It's ok I found the issue, a spelling mistake!

**Comment by HarrisrNZ** [comment]
What was the spelling mistake?
