### ISSUE TITLE
Improvements: Wiring and OTA

### ISSUE THREAD

**Issue by codedmind** [marthoc/GarHAge#22]
I think is a plus having a wire schematic.
The d5 for the reed switch is missing in the building topic, the reed switch, in my case but assume for everyone should have a wire to gnd and that is missing to.

After all the code put in place and the nodemcd a good improvement is that the code allow OTA updates.

Last, thanks for your code, is working very good.

**Comment by marthoc** [comment]
There are two sections in the instructions for wiring: one is "Building GarHAge", the other is "Installing GarHAge"; if you feel that these are incomplete feel free to suggest an improvement. I agree a wiring schematic would be helpful. 

Re the OTA updates, check the `dev` branch. OTA and more are included.

**Comment by HarrisrNZ** [comment]
Building GarHAge instructions are good. It is the integrating with home assistant that I am having issues with.
